#  **`NUMPY PART 3`**

In [1]:
import numpy as np

In [2]:
#array manipulation

In [4]:
arr = np.random.randint(1,10,(4,4))

In [5]:
arr

array([[8, 2, 1, 5],
       [1, 5, 6, 5],
       [8, 4, 1, 1],
       [7, 7, 2, 2]])

In [6]:
arr.reshape(8,2)

array([[8, 2],
       [1, 5],
       [1, 5],
       [6, 5],
       [8, 4],
       [1, 1],
       [7, 7],
       [2, 2]])

In [7]:
arr.T

array([[8, 1, 8, 7],
       [2, 5, 4, 7],
       [1, 6, 1, 2],
       [5, 5, 1, 2]])

In [9]:
arr.flatten()

array([8, 2, 1, 5, 1, 5, 6, 5, 8, 4, 1, 1, 7, 7, 2, 2])

In [10]:
arr

array([[8, 2, 1, 5],
       [1, 5, 6, 5],
       [8, 4, 1, 1],
       [7, 7, 2, 2]])

In [13]:
np.expand_dims(arr,axis=1) # increases the dimension across the axis

array([[[8, 2, 1, 5]],

       [[1, 5, 6, 5]],

       [[8, 4, 1, 1]],

       [[7, 7, 2, 2]]])

In [14]:
np.expand_dims(arr,axis=0)

array([[[8, 2, 1, 5],
        [1, 5, 6, 5],
        [8, 4, 1, 1],
        [7, 7, 2, 2]]])

In [15]:
data = np.array([[1],[2],[3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [20]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [21]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
#binary operations

In [24]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [25]:
arr1

array([[7, 1, 5, 1],
       [2, 4, 4, 6],
       [3, 3, 1, 6]])

In [26]:
arr2

array([[5, 4, 6, 3],
       [3, 6, 9, 9],
       [5, 3, 3, 5]])

In [27]:
arr1 + arr2

array([[12,  5, 11,  4],
       [ 5, 10, 13, 15],
       [ 8,  6,  4, 11]])

In [28]:
arr1 * arr2

array([[35,  4, 30,  3],
       [ 6, 24, 36, 54],
       [15,  9,  3, 30]])

In [29]:
arr1 / arr2

array([[1.4       , 0.25      , 0.83333333, 0.33333333],
       [0.66666667, 0.66666667, 0.44444444, 0.66666667],
       [0.6       , 1.        , 0.33333333, 1.2       ]])

In [30]:
arr1 - arr2

array([[ 2, -3, -1, -2],
       [-1, -2, -5, -3],
       [-2,  0, -2,  1]])

In [31]:
arr1**arr2

array([[   16807,        1,    15625,        1],
       [       8,     4096,   262144, 10077696],
       [     243,       27,        1,     7776]])

In [32]:
arr1

array([[7, 1, 5, 1],
       [2, 4, 4, 6],
       [3, 3, 1, 6]])

In [33]:
~arr1

array([[-8, -2, -6, -2],
       [-3, -5, -5, -7],
       [-4, -4, -2, -7]])

In [34]:
arr1 > arr2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [35]:
#String operations

In [36]:
arr = np.array(["sudh","kumar"])

In [37]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [38]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [39]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [40]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [41]:
# Mathematical functions

In [42]:
arr1

array([[7, 1, 5, 1],
       [2, 4, 4, 6],
       [3, 3, 1, 6]])

In [43]:
np.sin(arr1)

array([[ 0.6569866 ,  0.84147098, -0.95892427,  0.84147098],
       [ 0.90929743, -0.7568025 , -0.7568025 , -0.2794155 ],
       [ 0.14112001,  0.14112001,  0.84147098, -0.2794155 ]])

In [44]:
np.cos(arr1)

array([[ 0.75390225,  0.54030231,  0.28366219,  0.54030231],
       [-0.41614684, -0.65364362, -0.65364362,  0.96017029],
       [-0.9899925 , -0.9899925 ,  0.54030231,  0.96017029]])

In [45]:
np.tan(arr1)

array([[ 0.87144798,  1.55740772, -3.38051501,  1.55740772],
       [-2.18503986,  1.15782128,  1.15782128, -0.29100619],
       [-0.14254654, -0.14254654,  1.55740772, -0.29100619]])

In [46]:
np.log10(arr1)

array([[0.84509804, 0.        , 0.69897   , 0.        ],
       [0.30103   , 0.60205999, 0.60205999, 0.77815125],
       [0.47712125, 0.47712125, 0.        , 0.77815125]])

In [47]:
np.exp(arr1)

array([[1096.63315843,    2.71828183,  148.4131591 ,    2.71828183],
       [   7.3890561 ,   54.59815003,   54.59815003,  403.42879349],
       [  20.08553692,   20.08553692,    2.71828183,  403.42879349]])

In [48]:
np.power(arr1,3)

array([[343,   1, 125,   1],
       [  8,  64,  64, 216],
       [ 27,  27,   1, 216]], dtype=int32)

In [49]:
np.mean(arr1)

3.5833333333333335

In [50]:
np.median(arr1)

3.5

In [52]:
np.std(arr1)

2.0190069065976197

In [53]:
np.var(arr1)

4.076388888888889

In [54]:
np.min(arr1)

1

In [56]:
np.max(arr1)

7

In [57]:
# Arihtmetic operations

In [58]:
arr1

array([[7, 1, 5, 1],
       [2, 4, 4, 6],
       [3, 3, 1, 6]])

In [59]:
arr2

array([[5, 4, 6, 3],
       [3, 6, 9, 9],
       [5, 3, 3, 5]])

In [60]:
arr1 - arr2

array([[ 2, -3, -1, -2],
       [-1, -2, -5, -3],
       [-2,  0, -2,  1]])

In [61]:
np.subtract(arr1,arr2)

array([[ 2, -3, -1, -2],
       [-1, -2, -5, -3],
       [-2,  0, -2,  1]])

In [62]:
np.multiply(arr1,arr2)

array([[35,  4, 30,  3],
       [ 6, 24, 36, 54],
       [15,  9,  3, 30]])

In [64]:
np.mod(arr1,arr2) # remainder after division

array([[2, 1, 5, 1],
       [2, 4, 4, 6],
       [3, 0, 1, 1]])

In [65]:
np.power(arr1,arr2)

array([[   16807,        1,    15625,        1],
       [       8,     4096,   262144, 10077696],
       [     243,       27,        1,     7776]])

In [66]:
np.sqrt(arr1)

array([[2.64575131, 1.        , 2.23606798, 1.        ],
       [1.41421356, 2.        , 2.        , 2.44948974],
       [1.73205081, 1.73205081, 1.        , 2.44948974]])

In [67]:
# Statistical functions

In [68]:
np.mean(arr1)

3.5833333333333335

In [69]:
np.median(arr1)

3.5

In [70]:
np.std(arr1)

2.0190069065976197

In [71]:
np.var(arr1)

4.076388888888889