# **`NUMPY PART 4`**

In [1]:
import numpy as np

In [2]:
#sort , search and count functions

In [8]:
arr = np.array([4,2,5,1,6,3,9])

In [9]:
arr

array([4, 2, 5, 1, 6, 3, 9])

In [10]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 9])

In [12]:
np.searchsorted(arr,7)

6

In [29]:
arr1 = np.array([1,2,323,344,4334,444])

In [15]:
np.count_nonzero(arr1)

6

In [18]:
np.where(arr1>0)

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [20]:
np.extract(arr1>2,arr1)

array([ 323,  344, 4334,  444])

In [21]:
#byte swapping

In [22]:
arr1 

array([   1,    2,  323,  344, 4334,  444])

In [23]:
arr1.byteswap()

array([   16777216,    33554432,  1124139008,  1476460544,  -300941312,
       -1140785152])

In [24]:
arr1

array([   1,    2,  323,  344, 4334,  444])

In [25]:
arr1.byteswap(True)

array([   16777216,    33554432,  1124139008,  1476460544,  -300941312,
       -1140785152])

In [26]:
arr1

array([   16777216,    33554432,  1124139008,  1476460544,  -300941312,
       -1140785152])

In [27]:
# Copies and Views

In [31]:
arr1 = np.array([   1,    2,  323,  344, 4334,  444])

In [32]:
a = np.copy(arr1)

In [33]:
a

array([   1,    2,  323,  344, 4334,  444])

In [34]:
arr1

array([   1,    2,  323,  344, 4334,  444])

In [35]:
b = arr1.view() #shallow copy

In [36]:
b

array([   1,    2,  323,  344, 4334,  444])

In [37]:
b[0] = 234

In [38]:
b

array([ 234,    2,  323,  344, 4334,  444])

In [39]:
arr1

array([ 234,    2,  323,  344, 4334,  444])

In [40]:
# Matrix library

In [41]:
import numpy.matlib as nm

In [42]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [44]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [46]:
# linear algebra

In [49]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [50]:
arr1

array([[0, 2],
       [2, 0]])

In [51]:
arr2

array([[3, 0],
       [1, 0]])

In [52]:
np.dot(arr1,arr2)

array([[2, 0],
       [6, 0]])

In [53]:
arr1@arr2 #same as above

array([[2, 0],
       [6, 0]])