# **`NUMPY PART 1`**

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim

1

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [8]:
arr1 = np.array([[1,2,3,4],[2,3,4,5]])

In [9]:
arr1.ndim

2

In [11]:
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [14]:
matt= np.matrix(l)

In [17]:
np.asanyarray(matt) #matrix is already an array so anyarray will not do anythin

matrix([[1, 2, 3, 4, 5, 6]])

In [18]:
arr

array([1, 2, 3, 4, 5, 6])

In [19]:
a = arr

In [20]:
a

array([1, 2, 3, 4, 5, 6])

In [21]:
arr

array([1, 2, 3, 4, 5, 6])

In [22]:
arr[0] = 100

In [23]:
arr

array([100,   2,   3,   4,   5,   6])

In [24]:
a

array([100,   2,   3,   4,   5,   6])

In [25]:
b = np.copy(arr)

In [26]:
b

array([100,   2,   3,   4,   5,   6])

In [27]:
b[0] = 234

In [28]:
b

array([234,   2,   3,   4,   5,   6])

In [29]:
arr

array([100,   2,   3,   4,   5,   6])

In [30]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [35]:
iterable = (i*i for i in range(5))

In [37]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring("23,45,56",sep=",")

array([23., 45., 56.])

In [40]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [41]:
arr1.ndim

2

In [42]:
arr.size

6

In [43]:
arr.shape

(6,)

In [44]:
arr1.shape

(2, 4)

In [45]:
arr1.size

8

In [46]:
arr.dtype

dtype('int32')

In [47]:
arr1.dtype

dtype('int32')