# **`NUMPY PART 2`**

In [1]:
import numpy as np

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10))

TypeError: 'float' object cannot be interpreted as an integer

In [8]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [11]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [13]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
arr = np.ones((3,4))

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [26]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [28]:
arr = np.eye(5)

In [29]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [30]:
np.random.rand(2,3)

array([[0.93335264, 0.59523434, 0.95289609],
       [0.15142264, 0.84237608, 0.99153839]])

In [31]:
np.random.randn(2,3) # for normally distributed data

array([[ 0.65877423,  0.87470245,  0.10043206],
       [-0.84542404,  0.11972204, -0.89366406]])

In [33]:
arr2 = np.random.randint(1,5,(3,4))

In [38]:
arr2

array([[2, 1, 2, 1],
       [2, 4, 4, 2],
       [4, 1, 2, 2]])

In [35]:
arr2.size

12

In [36]:
arr2.shape

(3, 4)

In [37]:
arr2.reshape(6,2)

array([[2, 1],
       [2, 1],
       [2, 4],
       [4, 2],
       [4, 1],
       [2, 2]])

In [40]:
arr2.reshape(4,3)

array([[2, 1, 2],
       [1, 2, 4],
       [4, 2, 4],
       [1, 2, 2]])

In [41]:
arr2.reshape(4,-1) # -1 automatically takes the 2nd value. Any negative value works

array([[2, 1, 2],
       [1, 2, 4],
       [4, 2, 4],
       [1, 2, 2]])

In [44]:
arr2.reshape(2,2,3,1,1,1,1)

array([[[[[[[2]]]],



         [[[[1]]]],



         [[[[2]]]]],




        [[[[[1]]]],



         [[[[2]]]],



         [[[[4]]]]]],





       [[[[[[4]]]],



         [[[[2]]]],



         [[[[4]]]]],




        [[[[[1]]]],



         [[[[2]]]],



         [[[[2]]]]]]])

In [45]:
arr1 = np.random.randint(1,10,(5,6))

In [46]:
arr1

array([[2, 7, 9, 3, 8, 1],
       [8, 8, 7, 2, 6, 4],
       [9, 5, 1, 2, 1, 5],
       [9, 3, 1, 8, 7, 7],
       [4, 8, 4, 5, 6, 9]])

In [49]:
arr1 > 8

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False,  True]])

In [50]:
arr1[arr1 > 8]

array([9, 9, 9, 9])

In [51]:
arr1 

array([[2, 7, 9, 3, 8, 1],
       [8, 8, 7, 2, 6, 4],
       [9, 5, 1, 2, 1, 5],
       [9, 3, 1, 8, 7, 7],
       [4, 8, 4, 5, 6, 9]])

In [56]:
arr1[0,[0,1]]

array([2, 7])

In [65]:
arr1[2:4,[2,3]]

array([[1, 2],
       [1, 8]])

In [68]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [71]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [70]:
arr2

array([[1, 2, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [72]:
arr1 + arr2

array([[2, 4, 4],
       [3, 3, 2],
       [2, 4, 2]])

In [73]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1, -1,  0],
       [ 0,  0,  0]])

In [74]:
arr1 * arr2 #index wise multiplication not matrix 

array([[1, 4, 4],
       [2, 2, 1],
       [1, 4, 1]])

In [76]:
arr1@arr2 # for matrix multiplication

array([[ 7, 10,  6],
       [ 4,  6,  4],
       [ 6,  8,  5]])

In [77]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 0.5, 1. ],
       [1. , 1. , 1. ]])

In [78]:
arr1 /0 #infinity exists in numpy

C:\Users\tejas\AppData\Local\Temp\ipykernel_9384\306748856.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 /0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [79]:
#numpy boradcasting

In [80]:
arr = np.zeros((3,4))

In [83]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [82]:
arr + 5 #broadcasting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [84]:
a = np.array([1,2,3,4])

In [85]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [88]:
b= np.array([[3,4,5]])

In [100]:
arr1 = arr + b.T

In [101]:
b.T

array([[3],
       [4],
       [5]])

In [102]:
b.T.shape

(3, 1)

In [103]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [104]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [105]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [106]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [107]:
np.min(arr1)

3.0

In [108]:
np.max(arr1)

5.0