# **`ADABOOST GRADIENTBOOST AND XGBOOST IMPLEMENTATION`**

#### CLASSIFICATION

In [1]:
from sklearn.datasets import make_classification
X ,y = make_classification(n_samples=1000, n_features=4,
                          n_informative=2,n_redundant=0,
                          random_state=0,shuffle=False)

In [2]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [13]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [4]:
classifier1 = AdaBoostClassifier()
classifier1.fit(X_train,y_train)

AdaBoostClassifier()

In [6]:
y_pred1 = classifier1.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score , classification_report

In [8]:
print(confusion_matrix(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[153  13]
 [ 12 152]]
0.9242424242424242
              precision    recall  f1-score   support

           0       0.93      0.92      0.92       166
           1       0.92      0.93      0.92       164

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330



In [9]:
classifier2 = GradientBoostingClassifier()
classifier2.fit(X_train,y_train)

GradientBoostingClassifier()

In [10]:
y_pred2 = classifier2.predict(X_test)

In [11]:
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[153  13]
 [  7 157]]
0.9393939393939394
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330



In [14]:
classifier3 = XGBClassifier()
classifier3.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [15]:
y_pred3 = classifier3.predict(X_test)

In [16]:
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[155  11]
 [ 11 153]]
0.9333333333333333
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       166
           1       0.93      0.93      0.93       164

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330



#### REGRESSION

In [18]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000,n_features=4,
                      n_informative=2, random_state=0, shuffle=False)

In [19]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [20]:
from sklearn.ensemble import AdaBoostRegressor , GradientBoostingRegressor
from xgboost import XGBRegressor

In [21]:
regressor1 = AdaBoostRegressor()
regressor1.fit(X_train,y_train)

AdaBoostRegressor()

In [22]:
y_pred1 = regressor1.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error , r2_score
import numpy as np

In [26]:
print(mean_absolute_error(y_test,y_pred1))
print(mean_squared_error(y_test,y_pred1))
print(np.sqrt(mean_absolute_error(y_test,y_pred1)))
print(r2_score(y_test,y_pred1))

17.587761652918232
511.1705570571144
4.193776538266939
0.9314762719947208


In [27]:
regressor2 = GradientBoostingRegressor()
regressor2.fit(X_train,y_train)

GradientBoostingRegressor()

In [28]:
y_pred2 = regressor2.predict(X_test)

In [29]:
print(mean_absolute_error(y_test,y_pred2))
print(mean_squared_error(y_test,y_pred2))
print(np.sqrt(mean_absolute_error(y_test,y_pred2)))
print(r2_score(y_test,y_pred2))

5.436906058106717
66.5700986211643
2.3317174052845075
0.9910761070483729


In [30]:
regressor3 = XGBRegressor()
regressor3.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [31]:
y_pred3 = regressor3.predict(X_test)

In [32]:
print(mean_absolute_error(y_test,y_pred3))
print(mean_squared_error(y_test,y_pred3))
print(np.sqrt(mean_absolute_error(y_test,y_pred3)))
print(r2_score(y_test,y_pred3))

6.398100992754907
101.1233812476291
2.529446776027301
0.9864441506344184
