# **`LABEL and ORDINAL ENCODER`**

Label Encoding

In [2]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "color":["red","blue","green","green","red","blue"]
}
)

In [3]:
df

color
0    red
1   blue
2  green
3  green
4    red
5   blue

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
lbl_encoder = LabelEncoder()

In [6]:
lbl_encoder.fit_transform(df[["color"]])

c:\Users\tejas\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [7]:
lbl_encoder.transform([["red"]])

c:\Users\tejas\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2])

In [8]:
lbl_encoder.transform([["blue"]])

array([0])

In [9]:
lbl_encoder.transform([["green"]])

array([1])

## Ordinal encoding

In [12]:
## Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [13]:
#create dataframe
df = pd.DataFrame(
    {
    "size":["small","medium","large","medium","small","large"]
    }
)

In [14]:
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [15]:
## create an instance of ordinal encoder and perform fit_transform
encoder = OrdinalEncoder(categories=[["small","medium","large"]])

In [16]:
encoder.fit_transform(df[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [17]:
encoder.transform([["large"]])

c:\Users\tejas\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [18]:
encoder.transform([["small"]])

c:\Users\tejas\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])