 # **`LOGISTIC REGRESSION IMPLEMENTATION`**

In [2]:
import numpy as np
import pandas as pd
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import  load_iris

In [3]:
dataset = load_iris()

In [4]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [8]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [12]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
df["target"] = dataset.target

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
df_copy = df[df["target"] != 2]

In [20]:
df_copy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [56]:
df_copy.target.unique()

array([0, 1])

In [57]:
y = df_copy["target"]
X = df_copy.drop("target",axis=1)

In [58]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [59]:
X_train.shape , X_test.shape , y_train.shape, y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
classification = LogisticRegression(max_iter=200)

In [62]:
classification

LogisticRegression(max_iter=200)

In [63]:
classification.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [64]:
y_pred = classification.predict(X_test)

In [65]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion matrix , accuracy , classification report

In [66]:
from sklearn.metrics import confusion_matrix ,accuracy_score , classification_report

In [69]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [70]:
print(accuracy_score(y_test,y_pred))

1.0


In [71]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [72]:
from sklearn.model_selection import  KFold

In [77]:
cv = KFold(n_splits=5)

In [78]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [79]:
from sklearn.model_selection import cross_val_score

In [82]:
## these are the scores for all the cross validations
scores = cross_val_score(classification,X_train,y_train,scoring="accuracy",cv=cv)

In [83]:
np.mean(scores)

1.0

In [85]:
## Lets see one more example of complex data

# make a prediction with multinomial logistic model:
from sklearn.datasets import  make_classification
from sklearn.linear_model import  LogisticRegression
#define dataset
X,y = make_classification(n_samples=1000 ,n_features=10 , n_informative=5, n_classes=2, random_state=1)

In [86]:
X

array([[ 0.37647596, -1.12469218, -0.97947571, ..., -2.06316362,
        -0.83766139, -0.39781885],
       [ 0.04086182, -0.26156072,  1.73615405, ...,  0.16293878,
         1.36463935, -2.34248463],
       [ 1.34068549,  0.53299082,  0.60131262, ..., -0.65334123,
         2.70516706, -2.26814237],
       ...,
       [ 2.45229186, -1.66310304,  3.71533652, ..., -0.13022772,
         0.75551076, -0.1722673 ],
       [-0.65244646, -2.36974998,  1.9127131 , ..., -0.54693715,
         1.60875014, -4.01555464],
       [ 0.49044122, -1.39659014,  1.09593991, ...,  0.14844071,
         0.04846857, -1.2453332 ]])

In [87]:
y

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [90]:
complex_class_model = LogisticRegression(max_iter=200)

In [91]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [92]:
y_pred = complex_class_model.predict(X_test)

In [93]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[92 17]
 [27 64]]
0.78
              precision    recall  f1-score   support

           0       0.77      0.84      0.81       109
           1       0.79      0.70      0.74        91

    accuracy                           0.78       200
   macro avg       0.78      0.77      0.78       200
weighted avg       0.78      0.78      0.78       200



In [94]:
## Cross validation
cv = KFold(n_splits=5)
cross_val_score(complex_class_model,X_train,y_train,cv=cv)

array([0.78125, 0.79375, 0.8625 , 0.85625, 0.79375])