In [2]:
import tensorflow as tf

In [ ]:
tf.__version__

In [ ]:
ineuron = tf.constant(42)
ineuron

In [ ]:
ineuron.numpy()

In [ ]:
ineuron1 = tf.constant(1,dtype=tf.int64)
ineuron1.numpy()

In [ ]:
ineuron_x = tf.constant([[4,2],[9,5]])
print(ineuron_x)

In [ ]:
print('shape',ineuron_x.shape)
print(ineuron_x.dtype)

In [ ]:
print(tf.ones(shape=(2,3)))

In [ ]:
print(tf.zeros(shape=(3,2)))

In [ ]:
const2 = tf.constant([[3,4,5],[3,4,5]])
const1 = tf.constant([[1,2,3],[1,2,3]])
result = tf.add(const2,const1)
print(result)

In [ ]:
tf.random.normal(shape=(2,2),mean=0,stddev=1)

In [ ]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

In [ ]:
var0 = 24
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]]) # rank 3 tensor
var0 , var1 , var2

In [ ]:
float_var64 = tf.Variable(89,dtype=tf.float64)
float_var64.dtype

In [ ]:
var_reassign = tf.Variable(89.)
var_reassign

In [ ]:
var_reassign.assign(98.)
var_reassign

In [ ]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

In [ ]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_value[i,j]

In [ ]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_value[i,j]+added_value[i,j]

# Shaping a tensor

In [ ]:
tensor = tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(tensor.shape)

In [ ]:
tensor1 = tf.reshape(tensor,[2,6]) # 2rows and 6 cols
tensor2 = tf.reshape(tensor,[1,12]) # 1 row and 12 cols
tensor1

In [ ]:
tensor2

In [ ]:
tf.rank(tensor).numpy()

In [ ]:
tensor3 = tensor[1,0,2] # slice 1, row 0  , col 2
tensor3.numpy()

In [ ]:
print(tensor.numpy())

In [ ]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

In [ ]:
tensor3.dtype

In [ ]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

In [ ]:
tensor*tensor

# Broadcasting

In [ ]:
tensor4 = tensor*4
print(tensor4)

In [ ]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u , tf.transpose(matrix_v))

In [ ]:
tensor1 = tf.cast(tensor1,dtype=float)
print(tensor1)
i = tf.cast(tensor1,dtype=tf.int32)
print(i)

In [ ]:
j = tf.cast(tf.constant(4.9),dtype=tf.int32)
j

# raged tensors

In [ ]:
ragged = tf.ragged.constant([[5,2,6,1],[],[4,10,7],[8],[6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

# squared difference between 2 tensors

In [ ]:
varx = [1,3,5,7,11]
vary = 5
varz =tf.math.squared_difference(varx,vary)
varz

In [ ]:
numbers = tf.constant([[4.,5.],[7.,3.]])

In [ ]:
tf.reduce_mean(input_tensor = numbers)
# (4.+5.+7.+3.)/4 = 4.75

In [ ]:
tf.reduce_mean(input_tensor = numbers,axis=0)

In [ ]:
tf.reduce_mean(input_tensor = numbers,axis=0,keepdims=True) # to retain the rank

In [ ]:
tf.reduce_mean(input_tensor = numbers,axis=1)

In [ ]:
tf.reduce_mean(input_tensor = numbers,axis=1,keepdims=True)

In [3]:
tf.random.normal(shape=(3,2),mean=10,stddev=2,dtype=tf.float32,seed=None,name=None)
ran = tf.random.normal(shape=(3,2),mean=10,stddev=2)
print(ran)

tf.Tensor(
[[ 7.936143   7.8892508]
 [ 9.427551  10.27867  ]
 [ 7.3817525 16.236536 ]], shape=(3, 2), dtype=float32)


In [4]:
tf.random.uniform(shape=(3,2),minval=0,maxval=None,dtype=tf.float32,seed=None,name=None)


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6862329 , 0.3407545 ],
       [0.87350464, 0.8959546 ],
       [0.46968305, 0.8874899 ]], dtype=float32)>

In [7]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
ran2 = tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
print(ran1)
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [9]:
dice1 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice_sum = dice1 + dice2
resulting_matrix = tf.concat(values=[dice1,dice2,dice_sum],axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 2  2  4]
 [ 4  2  6]
 [ 1  4  5]
 [ 3  1  4]
 [ 5  5 10]
 [ 6  1  7]
 [ 1  3  4]
 [ 2  5  7]
 [ 3  6  9]], shape=(10, 3), dtype=int32)


In [10]:
t5 = tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)


In [12]:
i = tf.argmax(t5).numpy()
print('index of max:' , i)
print('Max element:',t5[i].numpy())

index of max: 3
Max element: 42


In [14]:
i = tf.argmin(t5,axis=0).numpy()
print('index of max:' , i)
print('Max element:',t5[i].numpy())

index of max: 7
Max element: -11


In [15]:
t6 = tf.reshape(t5,[3,3])
print(t6)

tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)


In [17]:
i = tf.argmax(t6,axis=0).numpy()
print('indices of max down rows:' , i)

indices of max down rows: [1 0 2]


In [18]:
i = tf.argmin(t6,axis=0).numpy()
print('indices of min down rows:' , i)

indices of min down rows: [2 2 0]


In [19]:
i = tf.argmax(t6,axis=1).numpy()
print('indices of max down cols:' , i)
i = tf.argmin(t6,axis=1).numpy()
print('indices of min down cols:' , i)

indices of max down cols: [1 0 2]
indices of min down cols: [0 1 1]


In [21]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
print(variable)
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


In [23]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x ** 2,5)+ y**2)

f2 = tf.function(f1)
x = tf.constant([4.,-5.])
y = tf.constant([2.,3.])

assert f1(x,y) == f2(x,y).numpy()

In [24]:
f2(x,y).numpy()

109.0

# Gradient calculation

In [26]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
  tape.watch(a)
  c=tf.sqrt(tf.square(a)+tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


In [27]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
  c=tf.sqrt(tf.square(a)+tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


In [28]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
  d2c_d2a = outer_tape.gradient(dc_da,a)
  print(d2c_d2a)

tf.Tensor(
[[0.14203143 0.3846457 ]
 [0.63471186 0.37015942]], shape=(2, 2), dtype=float32)
