# **`TensorFlow Fundamentals`**

**Part 1: Theoretical Questions**

1. What are the different data structures used in Tensorflow?. Give some examples.

In TensorFlow, the primary data structure used for computation is the tensor. Tensors are multi-dimensional arrays that can hold data of various types. They are the fundamental building blocks for creating and manipulating data in TensorFlow. Here are some examples of data structures used in TensorFlow:

1. **tf.Tensor**: The tf.Tensor is the core data structure in TensorFlow. It represents a tensor, which is a multi-dimensional array of elements of a specific data type. Tensors can have different ranks (number of dimensions) such as scalars, vectors, matrices, or higher-dimensional arrays.

2. **tf.Variable**: tf.Variable is a mutable tensor that can be used to store and update trainable parameters in a TensorFlow model. It allows you to define and manage variables that can be modified during training or optimization.

3. **tf.constant**: tf.constant is an immutable tensor that holds a constant value. It is typically used to store fixed values such as hyperparameters, model configurations, or other constant data.

4. **tf.SparseTensor**: tf.SparseTensor is a specialized tensor format used to efficiently represent sparse data, where most of the elements are zero. It stores only the non-zero values and their indices, reducing memory consumption and speeding up computations for sparse data.

5. **tf.RaggedTensor**: tf.RaggedTensor is a data structure for representing and manipulating ragged or nested tensors. It is useful for handling variable-length data, such as sequences or text data, where the lengths of the elements can vary.

6. **tf.TensorArray**: tf.TensorArray is a dynamic, variable-length array that allows you to store and manipulate tensors in a loop. It can be used to accumulate intermediate results during computation.

These are some of the commonly used data structures in TensorFlow. They provide flexibility and efficiency for various types of data and computation requirements in TensorFlow models and operations.

2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example

In TensorFlow, both constants and variables are used to store data, but they have some key differences in terms of their immutability and their usage within a computational graph. Let's explore the differences between TensorFlow constants and variables with an example:

In [12]:
import tensorflow as tf

# TensorFlow Constant
a = tf.constant(5)  # Creating a constant tensor with value 5

# TensorFlow Variable
b = tf.Variable(3)  # Creating a variable tensor with initial value 3

# TensorFlow operations
add_op = tf.add(a, b)  # Adding constant 'a' and variable 'b'
update_op = b.assign(tf.add(b,1))  # Incrementing the variable 'b' by 1
add_op_update = tf.add(a,update_op)

print("Result1 :", add_op.numpy())
print("Result2 :", add_op_update.numpy())


Result1 : 8
Result2 : 9


In the example above, we create a TensorFlow constant a with a value of 5 using tf.constant(5). Constants are immutable; their values cannot be changed once assigned. They are typically used to store fixed values such as hyperparameters or other constant data that remains the same throughout the execution of a TensorFlow graph.

On the other hand, we create a TensorFlow variable b with an initial value of 3 using tf.Variable(3). Variables are mutable; their values can be modified during the execution of a TensorFlow graph. Variables are commonly used to store and update trainable parameters, such as weights and biases, in machine learning models.

In the example, we perform TensorFlow operations by adding the constant a and the variable b using tf.add(a, b). The result is computed based on the initial values of a and b. However, we also have an update operation b.assign(tf.add(b, 1)), which increments the value of the variable b by 1. This update modifies the value of b for subsequent computations as reflected. Finally Reuslt1 yields 8 and Result2 with updated b value yields 9.

3. Describe the process of matrix addition, multiplication, and elementwise operations in TensorFlow.

In TensorFlow, matrix addition, multiplication, and elementwise operations are performed using the TensorFlow operations specifically designed for these computations. Let's explore each process in detail:

Matrix Addition:
Matrix addition in TensorFlow is performed using the tf.add() operation. The operation takes two tensors of the same shape and adds their corresponding elements elementwise. The resulting tensor will have the same shape as the input tensors.

Example:

In [22]:
import tensorflow as tf
import numpy as np

# Creating two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix addition
result = tf.add(matrix1, matrix2)
print(result)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


Matrix Multiplication:
Matrix multiplication in TensorFlow is performed using the tf.matmul() operation. The operation takes two tensors as input and performs matrix multiplication according to the mathematical rules of matrix multiplication. The shape of the input tensors must be compatible for matrix multiplication.

Example:

In [3]:
# Creating two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix addition
result = tf.matmul(matrix1, matrix2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Elementwise Operations:
Elementwise operations in TensorFlow operate on corresponding elements of tensors independently. Common elementwise operations include addition (tf.add()), subtraction (tf.subtract()), multiplication (tf.multiply()), division (tf.divide()), exponentiation (tf.pow()), and more. These operations allow performing computations element by element across tensors with compatible shapes.

Example:

In [4]:
# Creating two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix addition
result = tf.multiply(matrix1, matrix2)
print(result)

tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


**Part 2: Practical Implementation**

Task 1: Creating and Manipulating Matrices<br>
note: The shape of the matrices in the questions are being altered to facilitate the operations.

1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the
values of matrix A.

In [8]:
matrix_A = tf.random.normal(shape=(3,3))
print(matrix_A)

tf.Tensor(
[[-0.22465332  2.1055245  -0.8811136 ]
 [-0.13667789  0.80546653  2.050046  ]
 [ 0.05245926  1.6659833  -0.31453454]], shape=(3, 3), dtype=float32)


2. Create a Gaussian matrix B with dimensions 3x3, using TensorFlow's truncated_normal function. Display the values of matrix B.

In [14]:
matrix_B = tf.random.truncated_normal(shape=(3,3))
print(matrix_B)

tf.Tensor(
[[-0.18799683  0.32815868 -1.1195952 ]
 [ 0.7606417   1.1597407  -0.34711504]
 [-0.9129991   0.35354373  0.05197154]], shape=(3, 3), dtype=float32)


3. Create a matrix C with dimensions 2x3, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [17]:
matrix_C = tf.random.normal(shape=(2,3),mean=2 ,stddev=0.5)
print(matrix_C)

tf.Tensor(
[[1.7780722 1.9982818 1.3195624]
 [1.979469  2.229458  2.184272 ]], shape=(2, 3), dtype=float32)


4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [18]:
matrix_D = matrix_A + matrix_B
print(matrix_D)

tf.Tensor(
[[-0.41265017  2.4336832  -2.0007088 ]
 [ 0.62396383  1.9652072   1.7029309 ]
 [-0.86053985  2.019527   -0.262563  ]], shape=(3, 3), dtype=float32)






5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [19]:
matrix_E = tf.matmul(matrix_C ,matrix_D)
print(matrix_E)

tf.Tensor(
[[-0.62240225 10.919194   -0.50093704]
 [-1.3053801  13.609943   -0.73723674]], shape=(2, 3), dtype=float32)


**Task 2: Performing Additional Matrix Operations**

1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
function.

In [20]:
matrix_F = tf.random.uniform(shape=(2,2))
print(matrix_F)

tf.Tensor(
[[0.75307524 0.27121508]
 [0.86302936 0.3447578 ]], shape=(2, 2), dtype=float32)


2. Calculate the transpose of matrix F and store the result in matrix G.

In [21]:
matrix_G = tf.transpose(matrix_F)
print(matrix_G)

tf.Tensor(
[[0.75307524 0.86302936]
 [0.27121508 0.3447578 ]], shape=(2, 2), dtype=float32)


3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [27]:
matrix_H = tf.math.exp(matrix_F)
print(matrix_H)

tf.Tensor(
[[2.1235204 1.3115572]
 [2.3703303 1.4116479]], shape=(2, 2), dtype=float32)


4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [29]:
matrix_I = tf.concat(values=[matrix_F, matrix_G], axis=0)
print(matrix_I)

tf.Tensor(
[[0.75307524 0.27121508]
 [0.86302936 0.3447578 ]
 [0.75307524 0.86302936]
 [0.27121508 0.3447578 ]], shape=(4, 2), dtype=float32)






5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [30]:
matrix_J = tf.concat(values=[matrix_F, matrix_H], axis=1)
print(matrix_J)

tf.Tensor(
[[0.75307524 0.27121508 2.1235204  1.3115572 ]
 [0.86302936 0.3447578  2.3703303  1.4116479 ]], shape=(2, 4), dtype=float32)
